// Code generated by go-swagger; DO NOT EDIT.

// Copyright Prometheus Team
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package alert

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/prometheus/alertmanager/api/v2/models"
)

// NewOpenapiPostAlertsParams creates a new OpenapiPostAlertsParams object
// with the default values initialized.
func NewOpenapiPostAlertsParams() *OpenapiPostAlertsParams {
	var ()
	return &OpenapiPostAlertsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOpenapiPostAlertsParamsWithTimeout creates a new OpenapiPostAlertsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOpenapiPostAlertsParamsWithTimeout(timeout time.Duration) *OpenapiPostAlertsParams {
	var ()
	return &OpenapiPostAlertsParams{

		timeout: timeout,
	}
}

// NewOpenapiPostAlertsParamsWithContext creates a new OpenapiPostAlertsParams object
// with the default values initialized, and the ability to set a context for a request
func NewOpenapiPostAlertsParamsWithContext(ctx context.Context) *OpenapiPostAlertsParams {
	var ()
	return &OpenapiPostAlertsParams{

		Context: ctx,
	}
}

// NewOpenapiPostAlertsParamsWithHTTPClient creates a new OpenapiPostAlertsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewOpenapiPostAlertsParamsWithHTTPClient(client *http.Client) *OpenapiPostAlertsParams {
	var ()
	return &OpenapiPostAlertsParams{
		HTTPClient: client,
	}
}

/*OpenapiPostAlertsParams contains all the parameters to send to the API endpoint
for the openapi post alerts operation typically these are written to a http.Request
*/
type OpenapiPostAlertsParams struct {

	/*Alerts
	  The alerts to create

	*/
	Alerts models.PostableAlerts
	/*TenantID
	  ID of the tenant

	*/
	TenantID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the openapi post alerts params
func (o *OpenapiPostAlertsParams) WithTimeout(timeout time.Duration) *OpenapiPostAlertsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the openapi post alerts params
func (o *OpenapiPostAlertsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the openapi post alerts params
func (o *OpenapiPostAlertsParams) WithContext(ctx context.Context) *OpenapiPostAlertsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the openapi post alerts params
func (o *OpenapiPostAlertsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the openapi post alerts params
func (o *OpenapiPostAlertsParams) WithHTTPClient(client *http.Client) *OpenapiPostAlertsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the openapi post alerts params
func (o *OpenapiPostAlertsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAlerts adds the alerts to the openapi post alerts params
func (o *OpenapiPostAlertsParams) WithAlerts(alerts models.PostableAlerts) *OpenapiPostAlertsParams {
	o.SetAlerts(alerts)
	return o
}

// SetAlerts adds the alerts to the openapi post alerts params
func (o *OpenapiPostAlertsParams) SetAlerts(alerts models.PostableAlerts) {
	o.Alerts = alerts
}

// WithTenantID adds the tenantID to the openapi post alerts params
func (o *OpenapiPostAlertsParams) WithTenantID(tenantID string) *OpenapiPostAlertsParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the openapi post alerts params
func (o *OpenapiPostAlertsParams) SetTenantID(tenantID string) {
	o.TenantID = tenantID
}

// WriteToRequest writes these params to a swagger request
func (o *OpenapiPostAlertsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Alerts != nil {
		if err := r.SetBodyParam(o.Alerts); err != nil {
			return err
		}
	}

	// path param tenantId
	if err := r.SetPathParam("tenantId", o.TenantID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
