// Code generated by go-swagger; DO NOT EDIT.

// Copyright Prometheus Team
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package alert

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// OpenapiPostAlertsHandlerFunc turns a function with the right signature into a openapi post alerts handler
type OpenapiPostAlertsHandlerFunc func(OpenapiPostAlertsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn OpenapiPostAlertsHandlerFunc) Handle(params OpenapiPostAlertsParams) middleware.Responder {
	return fn(params)
}

// OpenapiPostAlertsHandler interface for that can handle valid openapi post alerts params
type OpenapiPostAlertsHandler interface {
	Handle(OpenapiPostAlertsParams) middleware.Responder
}

// NewOpenapiPostAlerts creates a new http.Handler for the openapi post alerts operation
func NewOpenapiPostAlerts(ctx *middleware.Context, handler OpenapiPostAlertsHandler) *OpenapiPostAlerts {
	return &OpenapiPostAlerts{Context: ctx, Handler: handler}
}

/*OpenapiPostAlerts swagger:route POST /openapi/{tenantId}/alerts alert openapiPostAlerts

Create new Alerts

*/
type OpenapiPostAlerts struct {
	Context *middleware.Context
	Handler OpenapiPostAlertsHandler
}

func (o *OpenapiPostAlerts) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewOpenapiPostAlertsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
